<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>coreworking_space_booking_backend</RootNamespace>
    <Company>PayMedia PVT Limited</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bc-xml-security-portable" Version="1.0.2" />
    <PackageReference Include="BCrypt.Net-Core" Version="1.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.19">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.19">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="PayMedia.DotNet.Utils.Logger" Version="6.0.4" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Seeds\" />
    <Folder Include="Assets\" />
    <Folder Include="Dtos\Requests\NewFolder\" />
    <Folder Include="Dtos\Requests\Role\" />
    <Folder Include="Dtos\Requests\Spaces\" />
    <Folder Include="Dtos\Responses\Role\" />
    <Folder Include="Dtos\Responses\Space\" />

    <Folder Include="Logs\" />
    <Folder Include="Middlewares\" />
    <Folder Include="Services\SpaceService\" />
    <Folder Include="wwwroot\uploads\" />
  </ItemGroup>

</Project>
